name: vaultlocker snap

on:
  - pull_request
  - push

jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Set up LXD
        uses: canonical/setup-lxd@v1

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Build snap
        run: snapcraft pack -v

      - name: Install snap
        run: sudo snap install --dangerous vaultlocker_*.snap

      - name: Verify snap help
        run: vaultlocker -h
